language: android
android:
  components:
    - android-27
    - build-tools-26.0.2
    - extra-google-google_play_services

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug testRelease createDebugUnitTestCoverageReport createReleaseUnitTestCoverageReport assembleAndroidTest
after_success:
  # Renaming folder and files of reports so codecov.io can find it
  - mv app/build/reports/jacoco/createDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
  - mv app/build/reports/jacoco/createReleaseUnitTestCoverageReport app/build/reports/jacoco/jacocoTestReleaseUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestReleaseUnitTestReport/createReleaseUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestReleaseUnitTestReport/jacocoTestReleaseUnitTestReport.xml
  - bash < (curl -s https://codecov.io/bash)
