language: android
android:
  components:
    - android-17
    - android-27
    - build-tools-26.0.2
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-17

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
  - emulator -avd test -engine classic -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest
